language: node_js
sudo: false
node_js:
  - '8'
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_dc7a46469796_key -iv $encrypted_dc7a46469796_iv -in blog_ci.enc -out blog_ci -d
  - mv blog_ci ~/.ssh/blog_ci
  - chmod 600 ~/.ssh/blog_ci
  - eval $(ssh-agent)
  - ssh-add -k ~/.ssh/blog_ci
  - cp ssh_config ~/.ssh/config
install:
  - npm install hexo-cli -g
  - npm install --save hexo-deployer-git
  - npm install
before_script:
  - git clone https://mizou:$mzpasswd@e.coding.net/likeer/hexo-next-xiuxiu/hexo-next-xiuxiu.git
script:
  - hexo clean
  - hexo g
  - hexo deploy


