language: node_js
sudo: false
node_js:
- '8'
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e879b6f1a992_key -iv $encrypted_e879b6f1a992_iv -in blog_ci.enc -out blog_ci -d
- mv blog_ci ~/.ssh/blog_ci
- chmod 600 ~/.ssh/blog_ci
- eval $(ssh-agent)
- ssh-add ~/.ssh/blog_ci
- cp ssh_config ~/.ssh/config
install:
- npm install hexo-cli -g
- npm install --save hexo-deployer-git
- npm install
before_script:
- git clone https://mizou:$mzpasswd@git.dev.tencent.com/mizou/hexo-next-xiuxiu.git themes/next
script:
- hexo clean && hexo g
- hexo deploy


